# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 28 Jan 2016 09:19:20 +0000
*               @ALL          1
*               @user         8
